#write a Program to print left, center and right justificationfor a given text (70 characters max columns)
string = input("Enter Your String to be centre Justified : ")
s = string.center(70)
print(s)
string1 = input("Enter Your String to be left Justified : ")
l = string1.ljust(70)
print(l)
string2 = input("Enter Your String to be right Justified : ")
r = string2.rjust(70)
print(r)